---
- name: Upgrade ubuntu from 22.04 to 24.04
  hosts: all
  become: true
  tasks:
    - name: Update Cache and Upgrade all packages to the latest version
      ansible.builtin.apt:
        force_apt_get: true
        upgrade: dist
        update_cache: true

    - name: Install the update-manager-core package if not already installed
      ansible.builtin.apt:
        name: update-manager-core
        state: present

    - name: Ensure the release-upgrades file is set to 'normal'
      ansible.builtin.lineinfile:
        path: /etc/update-manager/release-upgrades
        regexp: '^Prompt='
        line: 'Prompt=lts'

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if required
      ansible.builtin.reboot:
        msg: "Rebooting the server to complete the upgrade process."
        pre_reboot_delay: 10
      when: reboot_required.stat.exists
